// Run from the packages/mg-queue/ directory:
//   npx tsx examples/sqlite-reader.ts
// Requires a database generated by scripts/generate-sqlite-posts.sh first.
/* eslint-disable no-console */
import {Queue, Task, DynamicRenderer, SqliteReader} from '../src/index.js';
import {existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

const dbPath = fileURLToPath(new URL('../scripts/generated-posts.db', import.meta.url));
if (!existsSync(dbPath)) {
    console.log(`SQLite DB not found at ${dbPath}`);
    console.log('Run this first:\n  cd packages/mg-queue && bash scripts/generate-sqlite-posts.sh');
    process.exit(1);
}

const reader = new SqliteReader({dbPath});
await reader.configureForConcurrentAccess();

async function* generateTasks(batchSize: number): AsyncGenerator<Task> {
    for await (const row of reader.streamRowsById({
        table: 'posts',
        columns: ['id', 'title', 'body'],
        batchSize
    })) {
        const id = Number(row.id);
        const title = row.title;
        const body = row.body;

        yield {
            title: `Row ${id}: ${title}`,
            task: async () => {
                const wordCount = body.split(/\s+/).filter(Boolean).length;
                if (wordCount < 10 || wordCount > 20) {
                    throw new Error(`Unexpected word count ${wordCount} for row ${id}`);
                }

                await reader.updateRowById({
                    table: 'posts',
                    id,
                    values: {
                        title: title.toUpperCase()
                    }
                });
            }
        };
    }
}

const queue = new Queue({
    concurrency: 10,
    renderer: new DynamicRenderer()
});

try {
    const stats = await queue.run(generateTasks(2000));
    console.log(`Done: ${stats.completed} completed, ${stats.errors.length} failed`);
} finally {
    reader.close();
}
